
POST http://localhost:3120/uncompressed
Content-Type: application/json

[
  {
    "SET POINT HIGH HIGH": 153.9,
    "sapParentAvevaExternalId": "f2e0e22d-9bc0-4ec0-8b38-c3f98732a2d8",
    "Issued By": "Samit",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 12 oiu",
    "PART NUMBER": "uavr3ttm1o",
    "source": "ION",
    "flocBarrierElementPrimary": "ls0hapee0hcw",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "eed1d63a-d6c6-44b1-bcad-366cb2bb9454",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "4eml37qgpelr",
    "createdTime": "2023-08-25T18:12:24.270Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8969447,
    "flocFunctionalLocation": "c1iupcx56s",
    "WEIGHT (DRY)": 2.16,
    "MODEL NUMBER": "hz7z6p8",
    "I/O TYPE": "AO",
    "System": "77: Ventisjon Sys",
    "Discipline": "E: Electrical",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "bjhahvq87t",
    "flocSystemId": 35,
    "SET POINT HIGH HIGH_UOM": "iY",
    "flocLocation": "tgco",
    "SAP CATALOG PROFILE": "c5u54met",
    "FIRE AREA": "kjp1",
    "CALIBRATED RANGE MAX": 214.34,
    "LAST MAINTENANCE DATE": "2023-08-26T14:35:33.820Z",
    "CALIBRATION DATE": "2023-09-06T11:19:35.651Z",
    "LAST INSPECTION DATE": "2023-08-19T19:58:15.484Z"
  },
  {
    "SET POINT HIGH HIGH": 162.47,
    "sapParentAvevaExternalId": "91f1462f-9ff0-4fde-b2e2-f642d534c5e1",
    "Issued By": "Lisa",
    "SAP OBJECT TYPE": "IP-KJPT",
    "HAZARDOUS ATEX MARKING": "II 6 HJ",
    "PART NUMBER": "f9aomfyree",
    "source": "aveva",
    "flocBarrierElementPrimary": "c7qnl7niovs5",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "75fdc34a-a071-47ac-9fa2-1cd29c06f5ca",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "ikode7wdzc6a",
    "createdTime": "2023-09-13T10:37:14.658Z",
    "SUPPLY CODE": "NA",
    "state": "1",
    "id": 8421248,
    "flocFunctionalLocation": "xqmug5fm1d",
    "WEIGHT (DRY)": 3,
    "MODEL NUMBER": "lor7amf",
    "I/O TYPE": "DI",
    "System": "22: Sanitation Disposal system",
    "Discipline": "B: Biomarine and sanity",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "cucng69eol",
    "flocSystemId": 76,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "l29h",
    "SAP CATALOG PROFILE": "g5fglkjf",
    "FIRE AREA": "gg3l",
    "CALIBRATED RANGE MAX": 184.28,
    "LAST MAINTENANCE DATE": "2023-08-31T11:06:40.218Z",
    "CALIBRATION DATE": "2023-08-15T22:44:23.791Z",
    "LAST INSPECTION DATE": "2023-08-21T03:07:33.689Z"
  },
  {
    "SET POINT HIGH HIGH": 166.75,
    "sapParentAvevaExternalId": "3f58738e-b955-499a-9b35-7638bfe0e56a",
    "Issued By": "Dilanka",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 1 G",
    "PART NUMBER": "kutxwsgu0u",
    "source": "aveva",
    "flocBarrierElementPrimary": "g8m5s16trhtj",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "ede70e1d-747c-4227-bf88-d24fee96d7bf",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "ztaaqvpoz2di",
    "createdTime": "2023-08-28T16:38:11.376Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8825510,
    "flocFunctionalLocation": "vxh107yuwc",
    "WEIGHT (DRY)": 2.08,
    "MODEL NUMBER": "ua9vgjx",
    "I/O TYPE": "DO",
    "System": "32: Material uploading Sys",
    "Discipline": "A: Assemply and Installation",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "s10kvoap7f",
    "flocSystemId": 18,
    "SET POINT HIGH HIGH_UOM": "iY",
    "flocLocation": "ra9w",
    "SAP CATALOG PROFILE": "a3xl862w",
    "FIRE AREA": "c3py",
    "CALIBRATED RANGE MAX": 186.95,
    "LAST MAINTENANCE DATE": "2023-09-02T01:30:26.724Z",
    "CALIBRATION DATE": "2023-09-21T02:10:16.888Z",
    "LAST INSPECTION DATE": "2023-08-29T04:32:39.638Z"
  },
  {
    "SET POINT HIGH HIGH": 156.21,
    "sapParentAvevaExternalId": "40cf32fd-64cd-48a7-800d-7f5588642266",
    "Issued By": "Michael",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 12 oiu",
    "PART NUMBER": "ohfch4dw11",
    "source": "aveva",
    "flocBarrierElementPrimary": "21hcgpipkmn9",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "d7aed846-f9cd-4da0-8321-74e5205aaba2",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "64h7kkb6aq95",
    "createdTime": "2023-08-29T15:09:28.966Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8845798,
    "flocFunctionalLocation": "o62dofap99",
    "WEIGHT (DRY)": 2.05,
    "MODEL NUMBER": "ujd5d1z",
    "I/O TYPE": "AI",
    "System": "32: Material uploading Sys",
    "Discipline": "E: Electrical",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "irata0gd43",
    "flocSystemId": 3,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "h7r0",
    "SAP CATALOG PROFILE": "lvf79gye",
    "FIRE AREA": "9og5",
    "CALIBRATED RANGE MAX": 219.42,
    "LAST MAINTENANCE DATE": "2023-09-20T09:47:23.435Z",
    "CALIBRATION DATE": "2023-08-23T15:33:25.595Z",
    "LAST INSPECTION DATE": "2023-08-14T01:01:41.405Z"
  },
  {
    "SET POINT HIGH HIGH": 165.08,
    "sapParentAvevaExternalId": "5842f854-79f4-47a5-bfcb-0cb07478f13d",
    "Issued By": "Vaibhav",
    "SAP OBJECT TYPE": "IP-KJPT",
    "HAZARDOUS ATEX MARKING": "II 2 G",
    "PART NUMBER": "t673u4pbiv",
    "source": "ION",
    "flocBarrierElementPrimary": "tdske3yz216e",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "c7bd8670-e933-4aae-b4cf-addec023ebb2",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "aajb5b2bymfk",
    "createdTime": "2023-08-21T00:31:20.589Z",
    "SUPPLY CODE": "ASIA",
    "state": "0",
    "id": 8342157,
    "flocFunctionalLocation": "4wot1q18t9",
    "WEIGHT (DRY)": 2.95,
    "MODEL NUMBER": "49pl7qt",
    "I/O TYPE": "DO",
    "System": "22: GAS PROCESSING",
    "Discipline": "B: Biomarine and sanity",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "yyp6vp339b",
    "flocSystemId": 55,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "ba6b",
    "SAP CATALOG PROFILE": "51va51q9",
    "FIRE AREA": "q2pk",
    "CALIBRATED RANGE MAX": 204.57,
    "LAST MAINTENANCE DATE": "2023-08-21T19:29:30.912Z",
    "CALIBRATION DATE": "2023-08-25T05:11:45.405Z",
    "LAST INSPECTION DATE": "2023-08-16T15:44:41.248Z"
  },
  {
    "SET POINT HIGH HIGH": 161.33,
    "sapParentAvevaExternalId": "f34787bb-5e39-4d15-9a2e-4b3b52f067a7",
    "Issued By": "Vaibhav",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 6 HJ",
    "PART NUMBER": "5y719rvl5p",
    "source": "sap",
    "flocBarrierElementPrimary": "aubxv1j5olze",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "2c87dc4a-a5c1-4ded-856e-de8227fddf14",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "s0kvms3zcpsu",
    "createdTime": "2023-09-11T20:36:29.568Z",
    "SUPPLY CODE": "EU",
    "state": "1",
    "id": 8654081,
    "flocFunctionalLocation": "ppirivw29x",
    "WEIGHT (DRY)": 2.9,
    "MODEL NUMBER": "5kva1wh",
    "I/O TYPE": "AI",
    "System": "11: Crane and fabrication",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "y7gc20n153",
    "flocSystemId": 6,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "ti1v",
    "SAP CATALOG PROFILE": "60q2j300",
    "FIRE AREA": "ct0j",
    "CALIBRATED RANGE MAX": 208.99,
    "LAST MAINTENANCE DATE": "2023-08-14T00:29:15.762Z",
    "CALIBRATION DATE": "2023-09-04T20:22:02.420Z",
    "LAST INSPECTION DATE": "2023-08-13T08:58:19.576Z"
  },
  {
    "SET POINT HIGH HIGH": 167.36,
    "sapParentAvevaExternalId": "a87352f0-b04c-41cf-a66a-049959884a98",
    "Issued By": "Samit",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 12 oiu",
    "PART NUMBER": "6reaw7kwla",
    "source": "sap",
    "flocBarrierElementPrimary": "qwlqmkzebzyz",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "6fe418f0-f33b-4445-9f2d-cce817da3fc9",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "ly812jjywf5e",
    "createdTime": "2023-08-26T20:07:33.293Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8116134,
    "flocFunctionalLocation": "jwfgc2oitm",
    "WEIGHT (DRY)": 2.12,
    "MODEL NUMBER": "hsxieo8",
    "I/O TYPE": "AO",
    "System": "21: CRUDE HANDLING AND METERING",
    "Discipline": "G: Gaseous sabstances",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "65wdhq07ai",
    "flocSystemId": 23,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "v471",
    "SAP CATALOG PROFILE": "6hw0jy81",
    "FIRE AREA": "erlt",
    "CALIBRATED RANGE MAX": 191.68,
    "LAST MAINTENANCE DATE": "2023-08-26T04:58:48.126Z",
    "CALIBRATION DATE": "2023-08-16T06:51:23.289Z",
    "LAST INSPECTION DATE": "2023-09-01T20:51:39.780Z"
  },
  {
    "SET POINT HIGH HIGH": 164.18,
    "sapParentAvevaExternalId": "e607af3e-6462-42f0-a9d1-02ee178b2e51",
    "Issued By": "Dilanka",
    "SAP OBJECT TYPE": "IP-KJPT",
    "HAZARDOUS ATEX MARKING": "II 9 GIJO",
    "PART NUMBER": "y7h79y4eh9",
    "source": "sap",
    "flocBarrierElementPrimary": "w3ewtnyqyg1b",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "b2cdabf3-9a14-4f36-a00b-bd9101ef83c2",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "rlkmwllv0vxg",
    "createdTime": "2023-08-19T01:01:57.105Z",
    "SUPPLY CODE": "NA",
    "state": "1",
    "id": 8928789,
    "flocFunctionalLocation": "oqorwx687k",
    "WEIGHT (DRY)": 2.2,
    "MODEL NUMBER": "2pvj6p9",
    "I/O TYPE": "AO",
    "System": "22: GAS PROCESSING",
    "Discipline": "D: Gas and toxic substance",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "cx1dewmly9",
    "flocSystemId": 92,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "lfwa",
    "SAP CATALOG PROFILE": "y10mrky8",
    "FIRE AREA": "k1zo",
    "CALIBRATED RANGE MAX": 204.33,
    "LAST MAINTENANCE DATE": "2023-09-17T19:17:58.706Z",
    "CALIBRATION DATE": "2023-09-22T10:40:55.224Z",
    "LAST INSPECTION DATE": "2023-08-13T20:28:08.353Z"
  },
  {
    "SET POINT HIGH HIGH": 151.61,
    "sapParentAvevaExternalId": "9741a25e-60eb-4e93-a69b-d6c3dc812ccb",
    "Issued By": "Michael",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 4 F",
    "PART NUMBER": "p64bnetf1d",
    "source": "external",
    "flocBarrierElementPrimary": "nlj2wq407kun",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "59682b98-3de5-4bf6-862a-0c3e4249f5f0",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "ah19ncyrfhau",
    "createdTime": "2023-08-22T04:01:44.230Z",
    "SUPPLY CODE": "NA",
    "state": "1",
    "id": 8856788,
    "flocFunctionalLocation": "4kp0k8up6y",
    "WEIGHT (DRY)": 2.21,
    "MODEL NUMBER": "far7op0",
    "I/O TYPE": "DO",
    "System": "11: Crane and fabrication",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "ksxpryjj0j",
    "flocSystemId": 55,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "30fg",
    "SAP CATALOG PROFILE": "rua1vpjx",
    "FIRE AREA": "064q",
    "CALIBRATED RANGE MAX": 187.96,
    "LAST MAINTENANCE DATE": "2023-08-20T06:00:07.570Z",
    "CALIBRATION DATE": "2023-08-21T02:45:51.395Z",
    "LAST INSPECTION DATE": "2023-09-14T22:17:19.943Z"
  },
  {
    "SET POINT HIGH HIGH": 169.22,
    "sapParentAvevaExternalId": "6afdc369-3cba-41b0-b75c-aa60004dd6e8",
    "Issued By": "Lisa",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 39 OI",
    "PART NUMBER": "oeja1nxz0o",
    "source": "aveva",
    "flocBarrierElementPrimary": "q129okqguan4",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "9fb2ce66-4326-4864-866c-7280065c6dac",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "i3zqqguag9u4",
    "createdTime": "2023-08-23T01:17:27.044Z",
    "SUPPLY CODE": "EU",
    "state": "1",
    "id": 8444719,
    "flocFunctionalLocation": "3bcufxakut",
    "WEIGHT (DRY)": 2.54,
    "MODEL NUMBER": "hed0kf7",
    "I/O TYPE": "AI",
    "System": "31: Sub mechanical Sys",
    "Discipline": "I: Industrial equipments",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "sx4m7x0875",
    "flocSystemId": 16,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "4up1",
    "SAP CATALOG PROFILE": "1jc5logu",
    "FIRE AREA": "mbmv",
    "CALIBRATED RANGE MAX": 212.98,
    "LAST MAINTENANCE DATE": "2023-08-13T14:55:22.882Z",
    "CALIBRATION DATE": "2023-09-03T15:57:14.608Z",
    "LAST INSPECTION DATE": "2023-08-28T18:27:19.319Z"
  },
  {
    "SET POINT HIGH HIGH": 151.61,
    "sapParentAvevaExternalId": "531158e3-25f9-438e-91c5-7dd8f71fc937",
    "Issued By": "Haakon",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 39 OI",
    "PART NUMBER": "h3dyadtbyq",
    "source": "ION",
    "flocBarrierElementPrimary": "d8wh9r4nhqkd",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "99a43ece-dbea-4827-a5db-ab53d5260e3e",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "12y0nw8rjivs",
    "createdTime": "2023-09-20T01:27:31.622Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8447127,
    "flocFunctionalLocation": "sesguiew70",
    "WEIGHT (DRY)": 2.14,
    "MODEL NUMBER": "xyn6f8d",
    "I/O TYPE": "DI",
    "System": "21: CRUDE HANDLING AND METERING",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "zel185qvus",
    "flocSystemId": 44,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "fy7f",
    "SAP CATALOG PROFILE": "qsr7xjqs",
    "FIRE AREA": "givh",
    "CALIBRATED RANGE MAX": 194.49,
    "LAST MAINTENANCE DATE": "2023-09-15T22:42:58.945Z",
    "CALIBRATION DATE": "2023-08-31T12:13:14.574Z",
    "LAST INSPECTION DATE": "2023-09-03T15:53:40.253Z"
  },
  {
    "SET POINT HIGH HIGH": 164.25,
    "sapParentAvevaExternalId": "0ef48fe6-d5e0-4cf2-8fe1-d9b31c704ae9",
    "Issued By": "Samit",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 1 G",
    "PART NUMBER": "wrqebuc8fa",
    "source": "ION",
    "flocBarrierElementPrimary": "xu8cdyn6htde",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "a3a09c86-93ab-4be6-9801-fec2fea1fa3a",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "4c2ifr3jdmer",
    "createdTime": "2023-09-08T18:22:34.971Z",
    "SUPPLY CODE": "EU",
    "state": "1",
    "id": 8133115,
    "flocFunctionalLocation": "uyrvhdw1pc",
    "WEIGHT (DRY)": 2.09,
    "MODEL NUMBER": "wn791ow",
    "I/O TYPE": "DO",
    "System": "32: Material uploading Sys",
    "Discipline": "I: Industrial equipments",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "uujmnv1xt5",
    "flocSystemId": 81,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "l9gi",
    "SAP CATALOG PROFILE": "zcy27d28",
    "FIRE AREA": "wklx",
    "CALIBRATED RANGE MAX": 211.72,
    "LAST MAINTENANCE DATE": "2023-09-17T19:07:25.969Z",
    "CALIBRATION DATE": "2023-09-05T23:09:38.877Z",
    "LAST INSPECTION DATE": "2023-08-28T13:33:06.720Z"
  },
  {
    "SET POINT HIGH HIGH": 157.47,
    "sapParentAvevaExternalId": "b4e416b2-1f57-4756-8a33-4959cd5c86ab",
    "Issued By": "Lisa",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 39 OI",
    "PART NUMBER": "6rqy0dmpdu",
    "source": "external",
    "flocBarrierElementPrimary": "odtecr9wrq8z",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "c7e08d85-e54e-4c45-a88a-e93a64e57301",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "r9nl2t0zyveu",
    "createdTime": "2023-09-24T12:10:08.629Z",
    "SUPPLY CODE": "ASIA",
    "state": "0",
    "id": 8971904,
    "flocFunctionalLocation": "8gss21d3aq",
    "WEIGHT (DRY)": 2.74,
    "MODEL NUMBER": "f9on1aw",
    "I/O TYPE": "DO",
    "System": "22: GAS PROCESSING",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "8mkdcq9f27",
    "flocSystemId": 11,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "3csz",
    "SAP CATALOG PROFILE": "1nt5u5xa",
    "FIRE AREA": "vs30",
    "CALIBRATED RANGE MAX": 205.49,
    "LAST MAINTENANCE DATE": "2023-09-21T16:45:27.623Z",
    "CALIBRATION DATE": "2023-08-27T18:31:24.528Z",
    "LAST INSPECTION DATE": "2023-08-30T19:15:25.286Z"
  },
  {
    "SET POINT HIGH HIGH": 169.18,
    "sapParentAvevaExternalId": "5e46f86c-df29-4ad1-9b15-959add442a14",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 1 G",
    "PART NUMBER": "wuobhxrt2d",
    "source": "external",
    "flocBarrierElementPrimary": "icg59xhhf8bk",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "9c2e3774-5d46-42f1-a8fe-1f72a38b0acc",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "gv7qa03uaxbi",
    "createdTime": "2023-09-19T13:50:34.307Z",
    "SUPPLY CODE": "EU",
    "state": "1",
    "id": 8808157,
    "flocFunctionalLocation": "zfayebnar6",
    "WEIGHT (DRY)": 2.9,
    "MODEL NUMBER": "2wi09jf",
    "I/O TYPE": "AI",
    "System": "11: Crane and fabrication",
    "Discipline": "C: Crane and material",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "s4rffxn2jw",
    "flocSystemId": 43,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "3ga6",
    "SAP CATALOG PROFILE": "850yzgk0",
    "FIRE AREA": "w45s",
    "CALIBRATED RANGE MAX": 198.88,
    "LAST MAINTENANCE DATE": "2023-08-24T18:29:26.216Z",
    "CALIBRATION DATE": "2023-09-14T23:11:55.702Z",
    "LAST INSPECTION DATE": "2023-09-24T19:57:56.978Z"
  },
  {
    "SET POINT HIGH HIGH": 152.95,
    "sapParentAvevaExternalId": "9e449052-97d0-43cd-b540-3afe54c66c48",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 6 HJ",
    "PART NUMBER": "ls7vmq2bfq",
    "source": "external",
    "flocBarrierElementPrimary": "z3mglxfo290o",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "5fbd916d-c470-42ee-89bb-257368a6afa5",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "1wdzpz4gytbs",
    "createdTime": "2023-08-30T00:22:27.922Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8599698,
    "flocFunctionalLocation": "dk5wsbinoq",
    "WEIGHT (DRY)": 2.56,
    "MODEL NUMBER": "ou6awzy",
    "I/O TYPE": "DO",
    "System": "21: CRUDE HANDLING AND METERING",
    "Discipline": "D: Gas and toxic substance",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
    "PARENT TAG": "1iu8ypx9wz",
    "flocSystemId": 75,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "r6b2",
    "SAP CATALOG PROFILE": "602baeus",
    "FIRE AREA": "w3cc",
    "CALIBRATED RANGE MAX": 199.76,
    "LAST MAINTENANCE DATE": "2023-09-17T07:50:11.883Z",
    "CALIBRATION DATE": "2023-08-23T19:09:48.063Z",
    "LAST INSPECTION DATE": "2023-09-12T15:25:18.768Z"
  },
  {
    "SET POINT HIGH HIGH": 163.79,
    "sapParentAvevaExternalId": "d5861360-6ba3-4d0a-8961-a460bf28a8e9",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 39 OI",
    "PART NUMBER": "wpovygijps",
    "source": "ION",
    "flocBarrierElementPrimary": "amcverk0fh6o",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "7b345db5-1102-47ab-9b4e-d3709947bce0",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "dejycpvo2qn5",
    "createdTime": "2023-09-04T04:48:59.880Z",
    "SUPPLY CODE": "NA",
    "state": "1",
    "id": 8901103,
    "flocFunctionalLocation": "s9y885jyqk",
    "WEIGHT (DRY)": 2.7,
    "MODEL NUMBER": "fan1sjk",
    "I/O TYPE": "AO",
    "System": "22: GAS PROCESSING",
    "Discipline": "G: Gaseous sabstances",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "daryv00qs5",
    "flocSystemId": 11,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "upef",
    "SAP CATALOG PROFILE": "1ru32rvh",
    "FIRE AREA": "ga76",
    "CALIBRATED RANGE MAX": 207.82,
    "LAST MAINTENANCE DATE": "2023-09-20T18:24:36.729Z",
    "CALIBRATION DATE": "2023-08-19T02:54:27.803Z",
    "LAST INSPECTION DATE": "2023-08-31T16:56:28.078Z"
  },
  {
    "SET POINT HIGH HIGH": 157.71,
    "sapParentAvevaExternalId": "21d0242a-e2a1-45e7-b1d9-e27c3a64cd88",
    "Issued By": "Vaibhav",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 2 G",
    "PART NUMBER": "i8c2y3kbn4",
    "source": "ION",
    "flocBarrierElementPrimary": "n43rpykbgfvb",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "fee8d797-9004-4407-89f3-b23adb4976f4",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "kaf74ntxjpls",
    "createdTime": "2023-08-14T18:55:29.728Z",
    "SUPPLY CODE": "ASIA",
    "state": "1",
    "id": 8030761,
    "flocFunctionalLocation": "e0psjdl2k9",
    "WEIGHT (DRY)": 2.41,
    "MODEL NUMBER": "0v5zo5z",
    "I/O TYPE": "AO",
    "System": "44: Some other sys",
    "Discipline": "G: Gaseous sabstances",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "m2aelai30h",
    "flocSystemId": 44,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "vu9o",
    "SAP CATALOG PROFILE": "57pomatc",
    "FIRE AREA": "mdx8",
    "CALIBRATED RANGE MAX": 195.55,
    "LAST MAINTENANCE DATE": "2023-08-18T05:05:34.826Z",
    "CALIBRATION DATE": "2023-08-28T23:34:56.419Z",
    "LAST INSPECTION DATE": "2023-09-01T17:11:27.756Z"
  },
  {
    "SET POINT HIGH HIGH": 161.38,
    "sapParentAvevaExternalId": "e3d35415-39af-45b2-ac5a-830a39f73e5d",
    "Issued By": "Haakon",
    "SAP OBJECT TYPE": "IP-KJPT",
    "HAZARDOUS ATEX MARKING": "II 12 oiu",
    "PART NUMBER": "r4unv3hhnq",
    "source": "aveva",
    "flocBarrierElementPrimary": "x7ujwwwade8j",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "3cc47344-ec9f-4883-be44-2c7aba6aeef3",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "4ht2q3fwydh0",
    "createdTime": "2023-08-25T12:33:49.647Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8042994,
    "flocFunctionalLocation": "w2uhl69jx7",
    "WEIGHT (DRY)": 2.07,
    "MODEL NUMBER": "hr71qa7",
    "I/O TYPE": "DO",
    "System": "44: Some other sys",
    "Discipline": "E: Electrical",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "dzjexho1hj",
    "flocSystemId": 93,
    "SET POINT HIGH HIGH_UOM": "iY",
    "flocLocation": "lmss",
    "SAP CATALOG PROFILE": "7w637dx7",
    "FIRE AREA": "mtr8",
    "CALIBRATED RANGE MAX": 191.98,
    "LAST MAINTENANCE DATE": "2023-08-21T21:52:03.301Z",
    "CALIBRATION DATE": "2023-08-16T08:30:32.629Z",
    "LAST INSPECTION DATE": "2023-09-19T09:44:23.985Z"
  },
  {
    "SET POINT HIGH HIGH": 160.96,
    "sapParentAvevaExternalId": "786edcc3-77bc-4f39-8f62-9e9953b0ed65",
    "Issued By": "Samit",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 1 G",
    "PART NUMBER": "8v5xx1f869",
    "source": "ION",
    "flocBarrierElementPrimary": "vvp7p4z8cjwk",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "d151408b-b456-4905-a90f-1125b42900ee",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "x3uj9epkorfm",
    "createdTime": "2023-09-06T17:13:51.157Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8827642,
    "flocFunctionalLocation": "egeob13gn2",
    "WEIGHT (DRY)": 2.55,
    "MODEL NUMBER": "xy8vnk0",
    "I/O TYPE": "AI",
    "System": "44: Some other sys",
    "Discipline": "F: Facility handling",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "v5l2314mth",
    "flocSystemId": 22,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "x23x",
    "SAP CATALOG PROFILE": "rz69qsd0",
    "FIRE AREA": "ases",
    "CALIBRATED RANGE MAX": 204.73,
    "LAST MAINTENANCE DATE": "2023-08-16T23:19:34.657Z",
    "CALIBRATION DATE": "2023-09-19T01:14:51.781Z",
    "LAST INSPECTION DATE": "2023-08-25T01:13:17.589Z"
  },
  {
    "SET POINT HIGH HIGH": 168.48,
    "sapParentAvevaExternalId": "21128449-1126-4589-be7a-b7f4c36a57dc",
    "Issued By": "Michael",
    "SAP OBJECT TYPE": "IP-KJPT",
    "HAZARDOUS ATEX MARKING": "II 4 F",
    "PART NUMBER": "kqit4ypf3i",
    "source": "sap",
    "flocBarrierElementPrimary": "a5x5llpdlru0",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "dff325e0-e429-47f0-b96c-6e8578924786",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "mkifdslzrd2t",
    "createdTime": "2023-08-19T14:42:06.968Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8447821,
    "flocFunctionalLocation": "rl7shdkp54",
    "WEIGHT (DRY)": 2.33,
    "MODEL NUMBER": "1qde3ji",
    "I/O TYPE": "AO",
    "System": "11: Crane and fabrication",
    "Discipline": "D: Gas and toxic substance",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
    "PARENT TAG": "4ymqj6tall",
    "flocSystemId": 75,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "98fr",
    "SAP CATALOG PROFILE": "707d5jbg",
    "FIRE AREA": "bpje",
    "CALIBRATED RANGE MAX": 191.86,
    "LAST MAINTENANCE DATE": "2023-08-25T21:34:45.796Z",
    "CALIBRATION DATE": "2023-09-23T15:54:05.847Z",
    "LAST INSPECTION DATE": "2023-08-26T23:13:14.767Z"
  },
  {
    "SET POINT HIGH HIGH": 160.02,
    "sapParentAvevaExternalId": "89055fbe-37cd-4acc-ac82-7c73eca3f1a1",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 39 OI",
    "PART NUMBER": "gbqohnnbxj",
    "source": "sap",
    "flocBarrierElementPrimary": "3vmeafbnk28n",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "cd614f6e-af15-40cf-8356-523c8e7646bd",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "30xcuhg68qzb",
    "createdTime": "2023-09-21T00:15:18.274Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8900404,
    "flocFunctionalLocation": "fspp0wu2at",
    "WEIGHT (DRY)": 2.73,
    "MODEL NUMBER": "dtb47ft",
    "I/O TYPE": "AO",
    "System": "44: Some other sys",
    "Discipline": "D: Gas and toxic substance",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
    "PARENT TAG": "86shvc7yu3",
    "flocSystemId": 68,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "4ns7",
    "SAP CATALOG PROFILE": "8nz21qes",
    "FIRE AREA": "o8r3",
    "CALIBRATED RANGE MAX": 199.53,
    "LAST MAINTENANCE DATE": "2023-09-23T08:20:57.483Z",
    "CALIBRATION DATE": "2023-09-14T12:32:55.133Z",
    "LAST INSPECTION DATE": "2023-09-07T21:49:59.267Z"
  },
  {
    "SET POINT HIGH HIGH": 158.46,
    "sapParentAvevaExternalId": "d611e5fe-7a37-4861-8ef3-1dab68f1f134",
    "Issued By": "Dilanka",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 2 G",
    "PART NUMBER": "dtoyovgv8t",
    "source": "ION",
    "flocBarrierElementPrimary": "luh1fk5qqjo7",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "4b314f02-ecd6-48df-bb88-51f56351e855",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "78y3rytdhteo",
    "createdTime": "2023-08-18T16:48:17.288Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8497918,
    "flocFunctionalLocation": "5un5n3jdlt",
    "WEIGHT (DRY)": 2.65,
    "MODEL NUMBER": "boekk08",
    "I/O TYPE": "DI",
    "System": "22: Sanitation Disposal system",
    "Discipline": "A: Assemply and Installation",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "ob53vfh2kb",
    "flocSystemId": 29,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "yif0",
    "SAP CATALOG PROFILE": "g6v6prnz",
    "FIRE AREA": "olqe",
    "CALIBRATED RANGE MAX": 180.26,
    "LAST MAINTENANCE DATE": "2023-08-17T20:14:59.524Z",
    "CALIBRATION DATE": "2023-09-13T10:19:33.102Z",
    "LAST INSPECTION DATE": "2023-08-20T22:43:21.358Z"
  },
  {
    "SET POINT HIGH HIGH": 163.58,
    "sapParentAvevaExternalId": "20d4efe6-7422-4a18-b314-0214f2e460ca",
    "Issued By": "Michael",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 9 GIJO",
    "PART NUMBER": "seyyqowvak",
    "source": "external",
    "flocBarrierElementPrimary": "mwysl9coxxl6",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "148e0a7c-2873-4003-b62d-25b1db4ab083",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "fogbv60n2qjt",
    "createdTime": "2023-08-23T09:11:15.864Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8769255,
    "flocFunctionalLocation": "mg43hir94j",
    "WEIGHT (DRY)": 2.09,
    "MODEL NUMBER": "7cly1vn",
    "I/O TYPE": "DI",
    "System": "44: Some other sys",
    "Discipline": "F: Facility handling",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "9j4yicu3ne",
    "flocSystemId": 82,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "ue29",
    "SAP CATALOG PROFILE": "pd1vx36x",
    "FIRE AREA": "onya",
    "CALIBRATED RANGE MAX": 214.23,
    "LAST MAINTENANCE DATE": "2023-08-13T17:02:00.242Z",
    "CALIBRATION DATE": "2023-09-09T02:34:31.461Z",
    "LAST INSPECTION DATE": "2023-08-15T04:40:45.165Z"
  },
  {
    "SET POINT HIGH HIGH": 161.52,
    "sapParentAvevaExternalId": "bc8d6d18-9b07-4c31-9737-94db9ae51486",
    "Issued By": "Haakon",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 2 G",
    "PART NUMBER": "rvgvv6uyh9",
    "source": "sap",
    "flocBarrierElementPrimary": "3kgn9vbzb45z",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "aa775b5a-72d7-420c-8fb3-ab4179a901ec",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "byiafg8c1w5f",
    "createdTime": "2023-08-27T17:09:31.940Z",
    "SUPPLY CODE": "ASIA",
    "state": "1",
    "id": 8859430,
    "flocFunctionalLocation": "23lykqo73e",
    "WEIGHT (DRY)": 2.13,
    "MODEL NUMBER": "t9v6n6n",
    "I/O TYPE": "DI",
    "System": "21: CRUDE HANDLING AND METERING",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
    "PARENT TAG": "i1i6oe7d8q",
    "flocSystemId": 90,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "lf01",
    "SAP CATALOG PROFILE": "xwq6xcr7",
    "FIRE AREA": "viqu",
    "CALIBRATED RANGE MAX": 215.95,
    "LAST MAINTENANCE DATE": "2023-09-11T10:52:02.390Z",
    "CALIBRATION DATE": "2023-09-22T16:36:40.747Z",
    "LAST INSPECTION DATE": "2023-09-07T09:59:34.937Z"
  },
  {
    "SET POINT HIGH HIGH": 162.91,
    "sapParentAvevaExternalId": "6b809820-2f67-4f1a-b8a8-ef8838a548ce",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 3 G",
    "PART NUMBER": "f2m53lafjm",
    "source": "sap",
    "flocBarrierElementPrimary": "9j9svu69189l",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "5f7b7c70-81ac-4e58-a7dd-102abe82d817",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "jaj6jd00hijq",
    "createdTime": "2023-09-11T15:59:35.883Z",
    "SUPPLY CODE": "NA",
    "state": "1",
    "id": 8730988,
    "flocFunctionalLocation": "i7wa48cjwt",
    "WEIGHT (DRY)": 2.34,
    "MODEL NUMBER": "p8qjrml",
    "I/O TYPE": "AI",
    "System": "22: Sanitation Disposal system",
    "Discipline": "I: Industrial equipments",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "rkzqp7szun",
    "flocSystemId": 61,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "4104",
    "SAP CATALOG PROFILE": "rbda89zh",
    "FIRE AREA": "uodv",
    "CALIBRATED RANGE MAX": 183.61,
    "LAST MAINTENANCE DATE": "2023-09-12T20:14:02.038Z",
    "CALIBRATION DATE": "2023-08-26T20:21:45.300Z",
    "LAST INSPECTION DATE": "2023-09-06T09:20:12.570Z"
  },
  {
    "SET POINT HIGH HIGH": 152.84,
    "sapParentAvevaExternalId": "3b0f1173-24db-40c0-a08b-4b4449e74b0c",
    "Issued By": "Samit",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 4 F",
    "PART NUMBER": "fdjcrvihvb",
    "source": "ION",
    "flocBarrierElementPrimary": "cj67nz119bzv",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "f446e624-3ce2-43bd-8fa2-1c6f538d5e4d",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "q5hqo2zgyv7h",
    "createdTime": "2023-09-24T11:59:30.510Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8367915,
    "flocFunctionalLocation": "kc72zi97r6",
    "WEIGHT (DRY)": 2.35,
    "MODEL NUMBER": "dzovzwv",
    "I/O TYPE": "AO",
    "System": "44: Some other sys",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "j99fsja6mn",
    "flocSystemId": 33,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "26es",
    "SAP CATALOG PROFILE": "1z0bwguz",
    "FIRE AREA": "w2sm",
    "CALIBRATED RANGE MAX": 212.41,
    "LAST MAINTENANCE DATE": "2023-08-20T18:57:18.413Z",
    "CALIBRATION DATE": "2023-08-25T20:03:48.795Z",
    "LAST INSPECTION DATE": "2023-08-16T16:09:29.708Z"
  },
  {
    "SET POINT HIGH HIGH": 165.71,
    "sapParentAvevaExternalId": "70f504c8-37a9-47b3-9523-4db80013b210",
    "Issued By": "Samit",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 12 oiu",
    "PART NUMBER": "6zhph7n0yc",
    "source": "aveva",
    "flocBarrierElementPrimary": "fdc5nr55mn9t",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "501aea63-f609-47fa-8fde-cc9ba373472a",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "romn0rukpdkt",
    "createdTime": "2023-09-12T15:20:37.989Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8981767,
    "flocFunctionalLocation": "0580hitn1o",
    "WEIGHT (DRY)": 2.8,
    "MODEL NUMBER": "yzqs962",
    "I/O TYPE": "DI",
    "System": "77: Ventisjon Sys",
    "Discipline": "E: Electrical",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "0nuvm5d4za",
    "flocSystemId": 49,
    "SET POINT HIGH HIGH_UOM": "iY",
    "flocLocation": "s5q0",
    "SAP CATALOG PROFILE": "oe3jdl5b",
    "FIRE AREA": "5q63",
    "CALIBRATED RANGE MAX": 216.23,
    "LAST MAINTENANCE DATE": "2023-08-19T15:02:07.511Z",
    "CALIBRATION DATE": "2023-09-04T17:36:18.983Z",
    "LAST INSPECTION DATE": "2023-09-07T11:57:41.382Z"
  },
  {
    "SET POINT HIGH HIGH": 165.47,
    "sapParentAvevaExternalId": "d1145ea5-6054-4430-b62f-91df8a152407",
    "Issued By": "Haakon",
    "SAP OBJECT TYPE": "IP-KJPT",
    "HAZARDOUS ATEX MARKING": "II 2 G",
    "PART NUMBER": "bz2n35mwdj",
    "source": "sap",
    "flocBarrierElementPrimary": "0wtbc9nxhh6x",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "6ec96f0f-b97b-430e-8191-b9e7e9f57d1d",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "rmwx497xlwfs",
    "createdTime": "2023-09-03T15:46:29.328Z",
    "SUPPLY CODE": "ASIA",
    "state": "0",
    "id": 8742327,
    "flocFunctionalLocation": "vkp14q5frg",
    "WEIGHT (DRY)": 2.77,
    "MODEL NUMBER": "sz0gtk5",
    "I/O TYPE": "DO",
    "System": "32: Material uploading Sys",
    "Discipline": "G: Gaseous sabstances",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "331dw8sls2",
    "flocSystemId": 11,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "mfx8",
    "SAP CATALOG PROFILE": "n7o9f205",
    "FIRE AREA": "g1eg",
    "CALIBRATED RANGE MAX": 204.8,
    "LAST MAINTENANCE DATE": "2023-08-18T18:33:17.394Z",
    "CALIBRATION DATE": "2023-08-15T23:56:24.399Z",
    "LAST INSPECTION DATE": "2023-09-01T01:23:26.255Z"
  },
  {
    "SET POINT HIGH HIGH": 152.32,
    "sapParentAvevaExternalId": "b75809a7-b8a6-4e36-9cc8-30ef370e78e9",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 9 GIJO",
    "PART NUMBER": "n0i6d0n7ga",
    "source": "sap",
    "flocBarrierElementPrimary": "ycxylavoq2xs",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "58a13e6a-a14d-462e-b8b5-b16dc9fe70b8",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "lhjskvb9ebk2",
    "createdTime": "2023-08-16T21:41:27.851Z",
    "SUPPLY CODE": "NA",
    "state": "1",
    "id": 8125332,
    "flocFunctionalLocation": "vbf616ennc",
    "WEIGHT (DRY)": 2.24,
    "MODEL NUMBER": "y1q81sj",
    "I/O TYPE": "AO",
    "System": "22: GAS PROCESSING",
    "Discipline": "G: Gaseous sabstances",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "9wmra96l9d",
    "flocSystemId": 2,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "z0lv",
    "SAP CATALOG PROFILE": "iey554qc",
    "FIRE AREA": "i5gq",
    "CALIBRATED RANGE MAX": 200.4,
    "LAST MAINTENANCE DATE": "2023-08-21T12:49:09.499Z",
    "CALIBRATION DATE": "2023-09-16T13:47:44.009Z",
    "LAST INSPECTION DATE": "2023-09-18T08:27:19.607Z"
  },
  {
    "SET POINT HIGH HIGH": 157.8,
    "sapParentAvevaExternalId": "b3117211-c914-47ad-949b-365235879438",
    "Issued By": "Dilanka",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 4 F",
    "PART NUMBER": "lgf17gmby0",
    "source": "ION",
    "flocBarrierElementPrimary": "uy9mv6pw03if",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "55e1ff18-af93-43a8-a5f6-c1af752cedef",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "94aahq661oez",
    "createdTime": "2023-08-20T20:21:22.242Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8846163,
    "flocFunctionalLocation": "42bmwdt7mj",
    "WEIGHT (DRY)": 2.38,
    "MODEL NUMBER": "04g6exx",
    "I/O TYPE": "DO",
    "System": "23: UTILITIES",
    "Discipline": "C: Crane and material",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
    "PARENT TAG": "z8qcepnyox",
    "flocSystemId": 60,
    "SET POINT HIGH HIGH_UOM": "oF",
    "flocLocation": "bzhz",
    "SAP CATALOG PROFILE": "g9v6w8va",
    "FIRE AREA": "1cew",
    "CALIBRATED RANGE MAX": 213.92,
    "LAST MAINTENANCE DATE": "2023-09-06T14:24:01.154Z",
    "CALIBRATION DATE": "2023-08-12T22:12:17.190Z",
    "LAST INSPECTION DATE": "2023-08-16T13:49:27.522Z"
  },
  {
    "SET POINT HIGH HIGH": 153.96,
    "sapParentAvevaExternalId": "26104492-5e35-4e42-810f-7886f55082a5",
    "Issued By": "Vaibhav",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 6 HJ",
    "PART NUMBER": "xd6ace3ppe",
    "source": "aveva",
    "flocBarrierElementPrimary": "brwinlhfg1xg",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "771f22d5-60c5-47cc-bed4-b26abce0421e",
    "SIGNAL TYPE": "0-10V",
    "HAZARDOUS AREA CERT NUMBER": "lrq6gf8t5iuj",
    "createdTime": "2023-08-19T12:24:20.078Z",
    "SUPPLY CODE": "ASIA",
    "state": "1",
    "id": 8546547,
    "flocFunctionalLocation": "98lfv84pne",
    "WEIGHT (DRY)": 2.47,
    "MODEL NUMBER": "0rzgpk4",
    "I/O TYPE": "AO",
    "System": "22: GAS PROCESSING",
    "Discipline": "E: Electrical",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "xidc0v2v53",
    "flocSystemId": 63,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "zlic",
    "SAP CATALOG PROFILE": "rhyuyxzm",
    "FIRE AREA": "lpal",
    "CALIBRATED RANGE MAX": 204.69,
    "LAST MAINTENANCE DATE": "2023-09-08T20:49:46.854Z",
    "CALIBRATION DATE": "2023-09-12T22:05:35.231Z",
    "LAST INSPECTION DATE": "2023-08-31T16:28:53.136Z"
  },
  {
    "SET POINT HIGH HIGH": 159.96,
    "sapParentAvevaExternalId": "c4e6e755-649b-4a74-a42e-68a1ea35febe",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 2 G",
    "PART NUMBER": "lk12137evm",
    "source": "external",
    "flocBarrierElementPrimary": "cnhhzht7zplz",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "293d6297-f132-4598-ad87-1bc74fd97f71",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "f90hldvr0f42",
    "createdTime": "2023-09-07T12:54:05.968Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8816029,
    "flocFunctionalLocation": "pjexjcutlj",
    "WEIGHT (DRY)": 2.11,
    "MODEL NUMBER": "xpcy3j0",
    "I/O TYPE": "DO",
    "System": "77: Ventisjon Sys",
    "Discipline": "B: Biomarine and sanity",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "qdusqv1ujl",
    "flocSystemId": 19,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "o3bm",
    "SAP CATALOG PROFILE": "w4dzz9fk",
    "FIRE AREA": "ku7r",
    "CALIBRATED RANGE MAX": 183.82,
    "LAST MAINTENANCE DATE": "2023-08-27T10:15:20.704Z",
    "CALIBRATION DATE": "2023-09-11T10:04:16.743Z",
    "LAST INSPECTION DATE": "2023-09-14T08:34:21.051Z"
  },
  {
    "SET POINT HIGH HIGH": 150.71,
    "sapParentAvevaExternalId": "be84379e-6626-4890-b6ec-72f288614452",
    "Issued By": "Haakon",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 12 oiu",
    "PART NUMBER": "yzw004fl0d",
    "source": "sap",
    "flocBarrierElementPrimary": "pr2kmvmiiv5v",
    "CALIBRATED RANGE MAX_UOM": "oF",
    "SERIAL NUMBER": "58b4f64d-cc42-4e61-95fd-afcc00be49fb",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "3c6p2goc2cs3",
    "createdTime": "2023-08-14T01:42:30.041Z",
    "SUPPLY CODE": "ASIA",
    "state": "0",
    "id": 8035270,
    "flocFunctionalLocation": "h1dzm8g51m",
    "WEIGHT (DRY)": 2.62,
    "MODEL NUMBER": "1tvfewt",
    "I/O TYPE": "AO",
    "System": "23: UTILITIES",
    "Discipline": "B: Biomarine and sanity",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
    "PARENT TAG": "iz6a4o7xwg",
    "flocSystemId": 63,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "w3bo",
    "SAP CATALOG PROFILE": "xyx6hl2z",
    "FIRE AREA": "ped6",
    "CALIBRATED RANGE MAX": 200.28,
    "LAST MAINTENANCE DATE": "2023-08-23T17:10:01.126Z",
    "CALIBRATION DATE": "2023-09-04T14:32:40.078Z",
    "LAST INSPECTION DATE": "2023-09-07T16:05:36.231Z"
  },
  {
    "SET POINT HIGH HIGH": 159.35,
    "sapParentAvevaExternalId": "e98e95c6-f5f2-4abb-a0cf-2b063c1408ff",
    "Issued By": "Ole",
    "SAP OBJECT TYPE": "IP-TIUT",
    "HAZARDOUS ATEX MARKING": "II 6 HJ",
    "PART NUMBER": "806twhpgby",
    "source": "aveva",
    "flocBarrierElementPrimary": "e3vam8c84u9b",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "c94a77df-6059-4940-aaa8-2c8245d2bdd0",
    "SIGNAL TYPE": "4-20mA",
    "HAZARDOUS AREA CERT NUMBER": "wggi1q9svhgf",
    "createdTime": "2023-09-15T04:59:25.237Z",
    "SUPPLY CODE": "EU",
    "state": "0",
    "id": 8757164,
    "flocFunctionalLocation": "ixvy74k49y",
    "WEIGHT (DRY)": 2.71,
    "MODEL NUMBER": "os2rgn6",
    "I/O TYPE": "DO",
    "System": "22: Sanitation Disposal system",
    "Discipline": "I: Industrial equipments",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
    "PARENT TAG": "tvxxu60jym",
    "flocSystemId": 12,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "5omd",
    "SAP CATALOG PROFILE": "4hlgwz0l",
    "FIRE AREA": "9uzo",
    "CALIBRATED RANGE MAX": 213.03,
    "LAST MAINTENANCE DATE": "2023-09-13T07:54:54.134Z",
    "CALIBRATION DATE": "2023-09-15T04:41:52.447Z",
    "LAST INSPECTION DATE": "2023-09-11T09:13:29.513Z"
  },
  {
    "SET POINT HIGH HIGH": 169.16,
    "sapParentAvevaExternalId": "0492b7f3-41f8-4f92-9764-3772f36cde27",
    "Issued By": "Vaibhav",
    "SAP OBJECT TYPE": "IP-IOFT",
    "HAZARDOUS ATEX MARKING": "II 1 G",
    "PART NUMBER": "j80tf769ip",
    "source": "external",
    "flocBarrierElementPrimary": "rpdlz3xc8di2",
    "CALIBRATED RANGE MAX_UOM": "PoC",
    "SERIAL NUMBER": "7e99b7b2-d839-4a8d-a32f-295bb33f130e",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "dynleslswzok",
    "createdTime": "2023-08-18T13:21:08.718Z",
    "SUPPLY CODE": "EU",
    "state": "1",
    "id": 8410333,
    "flocFunctionalLocation": "4g1insls8a",
    "WEIGHT (DRY)": 2.04,
    "MODEL NUMBER": "6f6e4v6",
    "I/O TYPE": "AI",
    "System": "32: Material uploading Sys",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
    "PARENT TAG": "x2hor57hzq",
    "flocSystemId": 75,
    "SET POINT HIGH HIGH_UOM": "oL",
    "flocLocation": "96jx",
    "SAP CATALOG PROFILE": "w828s9cz",
    "FIRE AREA": "9wz6",
    "CALIBRATED RANGE MAX": 219.21,
    "LAST MAINTENANCE DATE": "2023-09-22T22:26:46.140Z",
    "CALIBRATION DATE": "2023-08-18T01:58:28.287Z",
    "LAST INSPECTION DATE": "2023-09-13T09:19:09.040Z"
  },
  {
    "SET POINT HIGH HIGH": 164.1,
    "sapParentAvevaExternalId": "6805a864-5f5f-4e5f-9d55-1898bac436b7",
    "Issued By": "Michael",
    "SAP OBJECT TYPE": "IP-KJPT",
    "HAZARDOUS ATEX MARKING": "II 12 oiu",
    "PART NUMBER": "ded20ifi6g",
    "source": "sap",
    "flocBarrierElementPrimary": "ivxezo6quoh5",
    "CALIBRATED RANGE MAX_UOM": "oC",
    "SERIAL NUMBER": "a0e557a8-ff0f-4ac3-8609-e258296ad3a0",
    "SIGNAL TYPE": "Modbus",
    "HAZARDOUS AREA CERT NUMBER": "zsp4j7mbi19n",
    "createdTime": "2023-08-30T18:30:57.653Z",
    "SUPPLY CODE": "NA",
    "state": "0",
    "id": 8573561,
    "flocFunctionalLocation": "5efltw88ha",
    "WEIGHT (DRY)": 2.2,
    "MODEL NUMBER": "jwp4yjx",
    "I/O TYPE": "DI",
    "System": "21: CRUDE HANDLING AND METERING",
    "Discipline": "J: Jagan and magan",
    "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
    "PARENT TAG": "l4edactk5x",
    "flocSystemId": 73,
    "SET POINT HIGH HIGH_UOM": "oC",
    "flocLocation": "yb7s",
    "SAP CATALOG PROFILE": "hip0rv6a",
    "FIRE AREA": "5n25",
    "CALIBRATED RANGE MAX": 210.4,
    "LAST MAINTENANCE DATE": "2023-09-04T13:26:46.449Z",
    "CALIBRATION DATE": "2023-08-23T02:45:35.569Z",
    "LAST INSPECTION DATE": "2023-09-08T10:08:34.881Z"
  }
]
